name: Publish documentation to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Clean repo name
        id: clrepo
        shell: bash
        run: echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - name: checks result
        shell: bash
        env:
          REPO: ${{ steps.clrepo.outputs.repository_name }}
        run: echo "repo: ${REPO}"