name: Checks up for Repo thingies
on:
  workflow_dispatch:
  push:
    branches:
      - test-action-reponame2

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Clean repo name
        id: clrepo
        shell: bash
        run: echo "::set-output name=repository_name::${GITHUB_REPOSITORY#${{ github.repository_owner }}/}"

      - name: checks result
        shell: bash
        run: echo "repo: ${REPO}"
        env:
          REPO: "some-static-string"
