name: GitHub Action self tests
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test:
    name: Test the action by building our own documentation.
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Make a static copy of the repository to reference the action from
        shell: bash
        run: |
          git clone . "../this-very-action"

      - uses: ./../this-very-action/
        name: Run this action on ${{ matrix.os }} without pushing data back.
        with:
          project-name: "Self-tests project for ${{ matrix.os }} environment"
          no-push-back: true